# Generated by Django 4.1.7 on 2023-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
